name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: test-project
  PROJECT_PATH: "."

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html
      - name: create and compress web artifact
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html
          tar czfv /tmp/web.tgz ../build
      - name: Upload web page artifact
        uses: actions/upload-artifact@v4
        with:
          name: web artifact
          path: /tmp/web.tgz
  build-docker:
    needs: export-web
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Download web page artifact
        uses: actions/upload-artifact@v4
        with:
          path: /tmp/web.tgz
      - name: compress web artifact
        run: |
          mkdir web
          tar xf /tmp/web.tgz web
          ls -al
          ls -al web
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker image build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wareagledocker/grematochi:latest
          file: docker/Dockerfile
